version: '3'

services:
  redis:
    image: redis/redis-stack-server:latest
    ports:
      - "6379:6379"
    networks:
      - mynetwork

  whisperapi:
    image: whisper-local # Assuming you have a Dockerfile for your whisperapi
    ports:
      - "8000:8000"
    networks:
      - mynetwork

  webapp:
    image: webapp-local # Assuming you have a Dockerfile for your whisperapi
    ports:
      - "8080:8080"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
