version: '3.8'
services:
  whisperapi:
    image: synopsia/whisperapi:1.2.6
    ports:
      - "8000:8000"
    networks:
      - whisper-network
    env_file:
      - ./.env
    depends_on:
      - redis
      - mongodb
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  webapp:
    image: synopsia/webapp:1.0.0
    ports:
      - "8080:8080"
    networks:
      - whisper-network
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redis/redis-stack-server
    volumes:
      - ./redis-conf:/usr/local/etc/redis/redis.conf
    command: redis-stack-server /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379" 
    networks:
      - whisper-network

  mongodb:
      image: mongo
      ports:
      - "27017:27017"
      networks:
      - whisper-network

networks:
  whisper-network:
    driver: bridge
