version: '3.8'
services:
  whisperapi:
    image: synopsia/whisperapi:1.0.4
    ports:
      - "8000:8000"
    networks:
      - whisper-network
    env_file:
      - ./.env
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  whisperapp:
    image: synopsia/webapp:0.0.3
    ports:
      - "8080:8080"
    networks:
      - whisper-network
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redis/redis-stack-server
    ports:
      - "6379:6379" 
    networks:
      - whisper-network

networks:
  whisper-network:
    driver: bridge
